name: CI
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, labeled, synchronize]
    branches:
      - main
  # push:
  #   branches:
  #     - main

jobs:
  docker-librom-image:
    uses: ./.github/workflows/docker_librom.yml
  docker-base-image:
    uses: ./.github/workflows/docker_base.yml
  pip-with-librom:
    runs-on: ubuntu-latest
    needs: [docker-librom-image]
    container:
      image: ghcr.io/llnl/pylibrom/pylibrom_env:latest
      options: --user 1001 --privileged
      volumes:
        - /mnt:/mnt
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Check out pylibROM
        uses: actions/checkout@v1
        with:
            submodules: 'true'
      - name: Git Submodules status
        run: |
            git submodule status
      - name: build
        run: |
            pip install -v --user -C"--build-option=install" -C"--build-option=--librom-dir=/env/dependencies/libROM" -C"--build-option=-v" ./
      - name: check install
        run: |
            python3 -c "import pylibROM"
      - name: test
        run: |
            cd tests
            echo run pyVector unit test
            pytest test_pyVector.py --verbose
            echo run pyMatrix unit test
            pytest test_pyMatrix.py --verbose
            mpirun -n 2 pytest test_pyMatrix.py --verbose
            echo run pyOptions unit test
            pytest test_pyOptions.py --verbose
            echo run pySVD unit test
            pytest test_pySVD.py --verbose
            echo run pyStaticSVD unit test
            pytest test_pyStaticSVD.py --verbose
            echo run pyIncrementalSVD unit test
            pytest test_pyIncrementalSVD.py --verbose
            echo run pyBasisGenerator unit test
            pytest test_pyBasisGenerator.py --verbose
            echo run pyBasisReader unit test
            pytest test_pyBasisReader.py --verbose
            echo run pyBasisWriter unit test
            pytest test_pyBasisWriter.py --verbose
            echo run pyDMD unit test
            pytest test_pyDMD.py --verbose
            mpirun -n 2 pytest test_pyDMD.py --verbose
            echo run pyDEIM unit test
            pytest test_pyDEIM.py --verbose
            echo run pyGNAT unit test
            pytest test_pyGNAT.py --verbose
            echo run pyQDEIM unit test
            pytest test_pyQDEIM.py --verbose
            echo run pyS_OPT unit test
            pytest test_pyS_OPT.py --verbose
            echo run pyUtilities unit test
            pytest test_pyUtilities.py --verbose
  cmake-with-librom:
    runs-on: ubuntu-latest
    needs: [docker-librom-image]
    container:
      image: ghcr.io/llnl/pylibrom/pylibrom_env:latest
      options: --user 1001 --privileged
      volumes:
        - /mnt:/mnt
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Check out pylibROM
        uses: actions/checkout@v1
        with:
            submodules: 'true'
      - name: Git Submodules status
        run: |
            git submodule status
      - name: build
        run: |
            mkdir build
            cd build
            cmake .. -DLIBROM_DIR=/env/dependencies/libROM
            make
      - name: check install
        run: |
            cd build
            python3 -c "import _pylibROM"
      - name: test
        run: |
            cd tests
            echo run pyVector unit test
            pytest test_pyVector.py --verbose
            echo run pyMatrix unit test
            pytest test_pyMatrix.py --verbose
            mpirun -n 2 pytest test_pyMatrix.py --verbose
            echo run pyOptions unit test
            pytest test_pyOptions.py --verbose
            echo run pySVD unit test
            pytest test_pySVD.py --verbose
            echo run pyStaticSVD unit test
            pytest test_pyStaticSVD.py --verbose
            echo run pyIncrementalSVD unit test
            pytest test_pyIncrementalSVD.py --verbose
            echo run pyBasisGenerator unit test
            pytest test_pyBasisGenerator.py --verbose
            echo run pyBasisReader unit test
            pytest test_pyBasisReader.py --verbose
            echo run pyBasisWriter unit test
            pytest test_pyBasisWriter.py --verbose
            echo run pyDMD unit test
            pytest test_pyDMD.py --verbose
            mpirun -n 2 pytest test_pyDMD.py --verbose
            echo run pyDEIM unit test
            pytest test_pyDEIM.py --verbose
            echo run pyGNAT unit test
            pytest test_pyGNAT.py --verbose
            echo run pyQDEIM unit test
            pytest test_pyQDEIM.py --verbose
            echo run pyS_OPT unit test
            pytest test_pyS_OPT.py --verbose
            echo run pyUtilities unit test
            pytest test_pyUtilities.py --verbose
  baseline:
    runs-on: ubuntu-latest
    needs: [docker-base-image]
    container:
      image: ghcr.io/llnl/pylibrom/pylibrom_env_base:latest
      options: --user 1001 --privileged
      volumes:
        - /mnt:/mnt
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Check out pylibROM
        uses: actions/checkout@v1
        with:
            submodules: 'true'
      - name: Git Submodules status
        run: |
            git submodule status
      - name: build
        run: |
            pip install ./
      - name: check install
        run: |
            export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/extern/libROM/dependencies/parmetis-4.0.3/build/lib/libparmetis/:$GITHUB_WORKSPACE/extern/libROM/dependencies/parmetis-4.0.3/build/lib/libmetis/
            python3 -c "import pylibROM"
      - name: test
        run: |
            export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/extern/libROM/dependencies/parmetis-4.0.3/build/lib/libparmetis/:$GITHUB_WORKSPACE/extern/libROM/dependencies/parmetis-4.0.3/build/lib/libmetis/
            cd tests
            echo run pyVector unit test
            pytest test_pyVector.py --verbose
            echo run pyMatrix unit test
            pytest test_pyMatrix.py --verbose
            mpirun -n 2 pytest test_pyMatrix.py --verbose
            echo run pyOptions unit test
            pytest test_pyOptions.py --verbose
            echo run pySVD unit test
            pytest test_pySVD.py --verbose
            echo run pyStaticSVD unit test
            pytest test_pyStaticSVD.py --verbose
            echo run pyIncrementalSVD unit test
            pytest test_pyIncrementalSVD.py --verbose
            echo run pyBasisGenerator unit test
            pytest test_pyBasisGenerator.py --verbose
            echo run pyBasisReader unit test
            pytest test_pyBasisReader.py --verbose
            echo run pyBasisWriter unit test
            pytest test_pyBasisWriter.py --verbose
            echo run pyDMD unit test
            pytest test_pyDMD.py --verbose
            mpirun -n 2 pytest test_pyDMD.py --verbose
            echo run pyDEIM unit test
            pytest test_pyDEIM.py --verbose
            echo run pyGNAT unit test
            pytest test_pyGNAT.py --verbose
            echo run pyQDEIM unit test
            pytest test_pyQDEIM.py --verbose
            echo run pyS_OPT unit test
            pytest test_pyS_OPT.py --verbose
            echo run pyUtilities unit test
            pytest test_pyUtilities.py --verbose
    
